# Lect 1 #


## Market discrete time ##


- Risky: return ukknown 
- Riskless: known at $t - \Delta t$
- Locally riskless interest - $r(t)$ the net rate of return berween $ t and t + \Delta $
-$ \Omega $ set of events

P-probability measure, distributon over risky assets defining investors' beliefs - **historical probability**

$$
\mathbb{E}^{\mathcal{P}} [ S(t)] = \sum_{w_k \in \Omega} S(t) (w_k) P (w_k) 
$$

## Information structure ##


- Definition of partition, finer/coarser
- **Information structure**: sum to the state space; refinement occurs over time, formally $\mathcal{P}_{t + \Delta t}$ is finer than $\mathcal{P}$ for all t. 
- $f^h_t$ denotes a node of the partition (h element of information set at time t)

## Information evolution ## 

- Risky quantity
 $$ \mathrm{X}: \Omega \to \mathbf{R} 
 $$

 - Known quantity? -> based on $\mathcal{P}$, we know its relaization. if $w_k, w_j \in f^t_h$, then $X(\omega_k) = X(\omega_j)$
 - $\mathbf{X}: \mathcal{P}_t \to \mathcal{R}$
- Conditioning on the element of the partition, X is known with certainty. In other words, X is P-measurable. **Define measurability!**


We need to define a sequence of random variables over time, so we turn to stochastic processes.

- Stochastic process: 

$$ Y = \{ Y(t) \}^T_{t = 0}
$$

such that 
$Y(t): \Omega \to \mathcal{R}$ is adapted to $\mathcal{P}$ if $Y(t)$ is $\mathcal{P}_t$ - measurable for all t. 

## Updating the expectation ## 

- Unconditional: 

$$ \mathbf{E}^Q [X] = \sum_{\omega_k \in \Omega} X(\omega_k) \mathbf{Q}(\omega_k) 
$$

- We can use conditional expectation to narrow down the outcomes, if we condition on the particular element $f^t_h$, formally:

$$\mathbf{Q}[\omega_k \mid f^t_h] = \frac{\mathbf{Q}[{\omega_k} \cap f^t+h]}{\mathbf{Q[f^t_h]}} = \begin{cases}
 \frac{\mathcal{Q}[\omega_k]}{\mathcal{Q}[f^t_h]} \; \text {if} \; \omega_k \in f^t_h \\[1pt]
 0 \; \text{otherwise} \end{cases}
 $$
 
 The idea is that we can infer the value of rv precisely if we know we are operating wihin a information subset f. 

 - Use $\mathbf{E}^Q [X \mid \mathcal{P_t}] (f^h_t) = \sum_{w_k \in f^h_t} X(\omega_k) \frac{\mathcal{Q}[\omega_k]}{\mathcal{Q}[f^t_h]}$ instead of unconditional prob. 

 - Conditioning on the set in $t = 0, \mathcal{P_0}$ does not modify the unconditional formula, no refinement occurs. 

 - Given that $X$ is $\mathcal{P_i}$-measurable, we can take it out of the expectation to obtain $\mathbf{E^Q [ \mathcal{X} \mid \mathcal{P_i}] = \sum_{\omega_k \in \Omega} X(\omega_k) \frac{\mathbf{Q}[\omega_k \mid f^t_h]}{\mathbf{Q}[f^t_h]} = \underbrace{\text{take out}}{\frac{X}{\mathbf{Q}[f^t_h]}} \sum_{\omega_k \in f^t_h} \mathbf{Q}[\omega_k]} = X(f^t_h)$
 `
## Properties of conditional expectation ## 

- Linearity
- Tower property

## Independent random variables ## 

- definition of independence of variable and information set wrt probability measure $\mathcal{P}$

- it holds that $X$ is independent of $\mathcal{P}_t$ wrt $Q$ iff X takes all possible number of realizations on any $f^t_h \iin \mathcal{P}_t$ (weak independence)

- $E^Q [ X \mid \mathcal{P}_t] (f^t_h) = E^Q [ X ]$ for all $f^t_h \in \mathcal{P}_t$

- **martingales**: 
$$ M = \{M(t) \}^T_{t=0} \; \text{adapted to} \; \mathcal{P} = \{ \mathcal{P_t} \}^T_{t = 0} \; \; \text{is a martingale if} \forall t_i, t_{i+1} \; \text{we have}
$$

$$ \mathbf{E}^Q [M(t_{t_{i+1}}) \mid \mathcal{P_{t_i}}] = M(t_i)
$$

- meaning: the best forecast of the process at time $t + \Delta t$ is the forecast itself at time $t$. 

## Risky vs riskless ## 


- Dynamic investment strategies: $v$ is a $d+1$ dimensional $\mathcal{P}$-adapted process $v_j = \{ v_j(t) \}^{T - \Delta t}_{t = 0}$ with $j = 0,1,...,d$ where $v_j(t)$ is the number of units of security $j$ at time $t$ based on information $\mathcal{F}_t$

- **Value Process**: the value process of $v$ is denoted by $V_v = \{ V_v(t) \}^T_{t = 0}$ is defined as the following stochastic process: 

$$V_v(t) = \begin{cases} v_0(t) B(t) + \sum_i^d v_i (t) S_i (t) \; \; t = 0, \dots, T - \Delta t \\ 
v_0(T - \Delta t) B(T) + \sum_{i = 1}^d v_i (T - \Delta t) S_i (T), \; \; t = T \end{cases}
$$

-Explanation: ??? 

- **Cash flow process**: 

$$C_v (t) = \begin{cases} - V_v(0) \text{ initial negative outflow to buy} \qquad t = 0 \\
v_0 (t - \Delta t) B(t) + \sum_{i = 1}^{d} v_i (t - \Delta t)S_i(t) - V_v (t) \qquad t = \Delta t, \dots, T - \Delta t \\
V_v(T) \qquad t = T \end{cases}
$$ 

-Explanation: ?? 

- **Self-financing strategies**: dynamic strategy is self financing if $C_v(t) = 0, \quad t = \Delta t, \dots, T - \Delta t$ It follows from definition of cash flow process:

$$ v_0 (t - \Delta t) B(t) + \sum_{i = 1}^{d} v_i (t - \Delta t)S_i(t) = V_v(t)
$$

- **Discounted Gain Process**: for strategy $v$ we call DGP $\{G_v\} = \{ G_v (t) \}^T_{t = 0}$  the stochastic process defined as: 

$$
G_v(t) = \begin{cases} \frac{V_v(t)}{B(t)} + \sum_{\tau = 0}^t
 \frac{C_v (\tau)}{B(\tau)} \qquad t = 0, \dots, T - \Delta t \\ 
 \sum_{\tau = 0}^T \frac{C_v(\tau)}{B(\tau)}, \qquad t = T \end{cases}
 $$


## Anomalies ##

- Violations of LOP: if there exist two dyn investment strategies $v$ and $v'$ delivering the same cash flows for all t $C_v(t) = C_{v'}(t)$ for all t but $V_v(0) \neq V_{v'}(0)$ 

- Arbitrage opportunities of the first type: 
if there exists a dynamic investment straetgy $v$ such that: 

$$\begin{enumerate} 
\item V_v(0) \leq 0 \text{ we sell an asset} 
\item C_v(t) \geq 0 \text{ for all t} 
\item \mathbf{P}(C_v(\tau)>0) > 0 \text{ for some } \tau.
$$

- explanation: suppose all C null but at least one positive, then the price must be positive so $V_v(0) > 0 $ necessarily. LOP -> arbitrage opportunities!

## Risk neutral probabilities vs no arbitrage ## 

- taking the PV of security j at time t
- equivalent probabilty measures: positive probabilities assigned to $Q$ imply positive probabilities assigned to $\mathcal{P}$ and vice versa. 
- Goal : find Q such that no arbitrage

# Lecture 3 #

- Dynamic investment strategies: 

$$ \text{d+1 dimensional} \mathcal{P}-\text{adapted process} v_j = \{v_j(t)\}_{t = 0}^{T - \Delta t}
$$

## Relevant market processes I ##

**Self-financing dynamic strategies**: if 

- $C_v(t) = 0$ for any $t \in \{ \Delta t, ... \}$
- 

## Risk neutral probability and no arbitrage ## 

- **Equivalent martingale**: a strictly positive probabiltiy $Q(w_k)$ s.t. the PV of each security for any point t is a Q-martingale - meanin at each point the expectation of future price based on current information $\mathcal{P_t}$ is the best prediction. **clarify the notion of partition and information sets again**

- $S_j(t) = E^Q (\frac{S_j(t + \Delta t)}{1 + r(t) \Delta t} \mid \mathcal{P}_t)$ for any t. We can take out the discount factor $1/(1 + r(t) \Delta t)$ and then write: 
- $ A E^Q (\frac{S_j(t + \Delta t) - S_j(t)}{S_j(t)}) = r(t) \Delta t$

- *Proposition*: given a probability $Q$, we have that $Q$ is an equivalent martingale measure, and the value and cashflow processes satisfy the formula. **Comments**: 

- the first point indicates the risk neutal probabilitiy, for which $S_j(t) = E^Q(\frac{S_j(t + \Delta)}{1 + r(t) \Delta t})$ must hold. 
- Second point, formula 1: write cash generating process as the difference in future cash flows and the value at t, obtain current value, then take expectation conditioning on info in $t$ and take these values out of the expectation. For self financing strategies (cash flows null), formula simplifies to the definition of martingale.
- Sec point, formula 2:**clarify**

## First fundamental theorem of asset pricing ##

**Statement** : in discrete time multi period fin market, the followig are equivalent: 
- market arbitrage free; 
- there exists a risk neutral probability measure $Q$

2 to 1: let Q be a risk neutral measure, then by contradiction: let there exist an arbitraging strategy **not clear, prove at home - what does G have to do with this?** 
1 to 2 : **complete!!**

## Dynamic completeness ## 

A **contingent claim** is ana $\mathcal{P}-$ adapted process where $X(t)$ is the cashflow generated by the contingent claim $X$ at time $t$. 

The **contingent claim** $X = \{ X(t) \}^T_{t = \Delta t}$ is **attainable** if exists a dynamic investment strategy $v$ s.t. 
$$ C_v(t) = X(t), \quad t = \Delta t, \dots, T 
$$

equivalently: 

$$ v_0(t) B(t + \Delta t) + \sum_j v_j(t) \frac{S_j(t + \Delta t)}{1 + r(t)\Delta t} - V(t) = X(t)
$$

- We say that a multi period fin market is **dynamically complete** id every contingent claim $X = \{ X(t) \}^{T}_{t = \Delta t}$ is attainable. 

## The second fundamental theorem of asset pricing ## 

In a discrete multi period fin market TFAE:

- market is both arbitrage free and dynamically complete
- there exists one and only one equivalent martingale measure 

## No arbitrage valuation of redundant securities ##

let 
- $\{ B, S_1, \dots, S_d \}$ - no arbitrage
- New X is redundant, there exists $v^X = \{ v^X (t) \}^{T - \Delta t}_{t = 0}$ sucht that $C_{v^x}(t) = X(t)$
- did not undetrstand, **clarify** 

**Pricing proposition**: 

if the new strategy is redundant, TFAE: 

- extended market is arbitrage free
- for every straetgy $v^X$ replicating the new security, we have $V_x(t) = V_{v^X}(t)$ the cost of replicating strategy must be the same as the price of the redundant security itelf 
- for every risk neutral prob measure $Q$, the prop shown before holds i.e. liquidation value at time t must be equivalent to expectation of sum of liquid value at time $t + \Delta t$ and the cash generating process at time $t + \Delta t$. 

## Valuation/replication of European options ## 

If derivative is a European derivative with maturity $T$, there are no intermediate cashflows: 

$$ X(t) = 0 \quad \text{for} t = \Delta t, \dots, T - \Delta t 
$$

**Clarify next!!**

## The binomial model ## 

- Riskless security price evolves according to: 

$$ r \Delta t = \frac{B(t + \Delta t) - B(t)}{B(t)} \text{ with constant }r
$$ 

- the risky security experiences a series of upward and downward movements $S(t) u$ and $S(t) d$ 

$$
\begin{array}{rcl}
 & \nearrow & S(t)u \\[0.4em]
S(t) & & \\[0.4em]
 & \searrow & S(t)d
\end{array}
$$

- $ S(t_n) = S(0) u^k d^{t_m - k} $ where $n$ are periods, k is the number of upward movements with the number of different relizations equal to $\binom{t_n}{k} p^k (1-p)^{t_n - k}$

## The risk neutral probability ##

Let $Q(up) = p$ and $Q(down) = 1 - p$ s.t.

$$ E^Q [\frac{S(t + \Delta) - S(t)}{S(t)} \mid \mathcal{P}_t] = r \Delta t 
$$

$$ \frac{S(t) u - S(t)}{S(t)} q + \frac{}
$$ 

**understand arbitrage**

## American option ## 

- can be exercised at any $t \leq \tau \leq T$
- ex.: $X(t) = (K - S(t))^+$ maturity t, where $K$ is the strike price
- the payoff can be exercised at $t \in \{ \Delta t, \dots, T \}$
- discounted value of the option at $t$ at $r \geq t$ has price NA-value $E^Q_t [\hat{X} (\tau)]$
- $\tilde{V}_x(t) = \operatorname{max}_{t \leq \tau \leq T} E^Q_t [\tilde{X} (\tau)]$

$$ \tau: \Omega \to \{ \Delta t, 2 \Delta t, \dots, T \} 
$$ where omega is the event space.

$$\{r = t \} = \{ w \in \Omega: \tau(w) = t \} \in \mathcal{P}_t
$$ 

$$ \{ \tau \leq t \} \in \mathcal{P}_t 
$$ 

- Comment: we exercise based on current and past info $\mathcal{P}_t$ ?? **clarify** and **r is  a stoppin gtime wrt $\mathcal{P}$ what?? 

- $\tilde{V}_X(t) = \operatorname{max} (\tilde{X}(t), E_T^Q [\tilde{V}_X (t + \Delta t) \mid \mathcal{P}_t])$ where $\tilde{X} (t)$ is the immediate discounted value, and the $E_T^Q [\tilde{V}_X (t + \Delta t)]$ is the disocounted continuation value. **clarify discounted and continuation!!** the two quantitites are variable: $\tilde{X} (t) $ stands for the amount we stand to realize upon exercising the option immefiately, while the continuation value is the value exercised a little after.
- we should consider the risk preferences of the investor. We assume that market is frictionless.  
- Monte Carlo does not function as well for American option as for European option, because of the choice between immediate and continuation values 
- **Properties**: First property  $\tilde{V}_X (t) \geq \tilde{X} (t)$ Second property $\tilde{V}_{X_am}(t) \geq \tilde{V}_{EU}(t)$ because we are maximising $E_T^Q [\tilde{X} \mid \tau]$ over all set $t < \tau < T$.
- For EU options, $\tilde{V}_E$ is a Q-martingale with $\tilde{V}_E(t) = E^Q_t [\tilde{V}_E (t + \Delta t)]$
- Third property: $\tilde{V}_X$ is a **Q-supermartingale**, implying $\tilde{V}_X(t_1) \geq E^Q_{t_1} [\tilde{V}_X (t_2)]$: this follows from the American option recursion that we defined (choose max between immediate and continuation value). 
- fourth property: $\tau^*$ optimal exercise date, we have $\tau^* = \operatorname{min} \{t \in \{ \Delta t, \dots, T \}: \tilde{V}_X(t) = \tilde{X}(t) \}$ **follows from supermartingale property**
- **Early exercise Premium** (EEP): $EEP(t) = \tilde{V}_X(t) - \tilde{V}_E(t) \geq 0$

$$ \tilde{V}_X(t) = \tilde{V}_E (t) + EEP(t) 
$$ 

$$E^Q [\tilde{V}_X(t)] = E^Q [\tilde{V}_E(t)] + E^Q [EEP(t)] 
$$ where the latter term is *decreasing* in t and the former is constant. 

$$ E^Q(\tilde{V}_X (t_1) ) \geq E^Q (\tilde{V}_X (t_2)) \quad t_2 > t_1
$$

# Lecture 4 # 

## Recap of concepts ## 
- Recap: $r \in \{ \Delta t, \Delta t + 1, ..., T\}$ is the exercise date (for American option)
- Optimization yields $\tilde{V}_X(t) = \oepratorname{sup}_{t \leq r \leq T} E^Q_t(\tilde{X}(r))$
- Properties:
    1.  Supermartingale 
    2. $V(t is decreasing)$ in $E^Q$
    V(t is decreasing) intuition difference: ???**not clear difference between conditional and unconditional in terms of valuation** 
    3. $\tilde{V}_x (t) \geq \tilde{X} (t) \; \forall t $ 
    4. $\tilde{V}_x (t) \geq \tilde{V}_E (t)$ where E stands for European option
    5. $\tilde{V}_x$ is the smallest Q-supermartingale dominating $\tilde{X}$
    6. The optimal exercise date $\hat{r}$ satisfies: 

    $$ \hat{r} = \operatorname{inf}\{t \geq 0: \tilde{V}_X (t) = \tilde{X}(t) \} \text{ where X is the instantaneous payoff at t}
    $$ 

 
## Backward recursion comp of option value ## 

$$
\begin{aligned}
\tilde{V}_X(t) &= \tilde{X}(t), \\
t &= T - \Delta t, T - \Delta, ... , \Delta t \\ 
\tilde{V}_x (t) = \operatorname{max} \{ \tilde{X} (t), E^Q_t [\tilde{V}_X (t + \Delta)] \}
\end{aligned}
$$

From backward recursion: 

$$  \tilde{V}_x (t) \begin{cases} E^Q_t (\tilde{V}_x (t + \Delta t)) > \tilde{X}(t) \quad \text{continuation region, implying that V is a Q-martingale} \\[1em]
\tilde{X} (t) \geq E^Q_t(\tilde{V}_X (t + \Delta t) ) \quad \text{early exercise region, implying that V is a Q-supermartingale} \end{cases} 
$$

## Replicating the American option ## 

- Portfolio-Consumption pair $\phi = (v, c)$ where $v$ is the self financing strategy, c is consumption; 
- $v = (v_0, v_1) \quad X(t) = (K - S(t))^{+} \text{ put option in S}$
- $V_v(t + \Delta t) = v_0 (t) B(t + \Delta) + v_1 (t) S(t + \Delta t)$ the intertemporal budget constraint of the self financing strategy. It can also be rewritten as: 
$$ \Delta V_v (t) = v_0 (t) \Delta B(t) + v_1 (t) \Delta S (t)
$$

or, doscounting: 

$$ \Delta \tilde{V}_v (t) = \Delta \tilde{S} (t) 
$$

Cumulative consumption: 
$C(t) = \text{ consumption in }[0, t]$
We restrict the strategy only to cash withdrawal: 

$$ \Delta \tilde{C} (t) = \tilde{C} (t + \Delta t) - \tilde{C} (t) \geq 0 \; \forall t
$$ 

**Note**: $\tilde{C} (t) \text{ is } \mathcal{P}_t- \text{measurable}$

The value of $\phi$ (portfolio) 

$$ \begin{align} \tilde{V}_{\phi} (t) &= \tilde{V}_v (t) \\ 
\Delta \tilde{V}_{\phi} (t) &= \tilde{V}_{\phi} (t + \Delta t) - \tilde{V}_{\phi} (t) \end{align}
$$

**Why not withdraw money?** clarify (not optimal to hold more than the necessary amount to replicate the option?)

The goal of the writer is to find $\phi$ s.t. $\tilde{V}_{\phi} (t) \geq \tilde{X} (t) \quad \forall t  $

Claim: $\tilde{V}_{\phi}$ is a Q-supermartingale, i.e. $ E^Q_t [ \Delta \tilde{V}_{\phi} (t)] \leq 0 $
Indeed: we have $E^Q_t (\Delta \tilde{V}_{\phi} (t)) = E^Q_t [ \Delta \tilde{V}_v (t) - \Delta \tilde{C} (t)] = E^Q_t [\Delta \tilde{V}_v (t)] - E^Q_t [ \Delta \tilde{C} (t)] = - \Delta \tilde{C} (t) $  since the first term vanishes by the faxt that $\tilde{V}_v$ is Q martingale. 

The optimal portfolio $\phi^{*}$ satisfies: 

$$\tilde{V}_{\phi^*} (t) \geq \tilde{X} (t) \; \forall
$$ 

and we have $\tilde{V}_{\phi} = \tilde{V}_X$ (**clarify!!**)

We have: 

$$ \tilde{V}_{v^*} (t + \Delta t) = v^*_0 (t) + v^*_1 (t) \tilde{S} (t + \Delta t) - \Delta \tilde{C}^* (t) 
$$  

and 
$$ \Delta \tilde{C}^{*}(t) = - E^Q_t [ \Delta \tilde{V}_{\phi^{*}} (t)] = - E^Q_t [ \Delta \tilde{V}_X (t) ] = \begin{cases}
0, & \text{if \(V\) is in the continuation region}, \\[4pt]
{}>0, & \text{if \(V\) is in the early-exercise region}.
\end{cases}
$$

## European barrier option ## 

- X final payoff at t
- $S(0) < b$ is the barrier
- S is the stock/index that triggers the barrier 

The payoff is specified: 

$$ X_{ko} (t)  = \begin{cases} 0 \text{ if triggered } \\ 
X \text{ if not triggered} \end{cases}
$$

Or (knock in)

$$ X_{ko} (t)  = \begin{cases} X \text{ if triggered } \\ 
0 \text{ if not triggered} \end{cases}
$$

Define the running max of S :

$$ \begin{align} M(t) &= max\{ S(u): u \leq t \} \text{ running max of S for } u \in (0,t) \\ 
X_{KO} &= \begin{cases} 0 \text{ if } S \geq b \\ 
X \text{ othereise} \end{cases} \\ 
X &= X_{KI}(t) + X_{KO} (t) \\ 
V(t) &= V_{KI} (t) + V_{KO} (t) \end{align}
$$


We can apply backward recursion to barrier options: 

$$ \hat{V}_{KO} (t) = X \mathbf{1}(S(t) < b)
$$

Now, we want to prove that we can use the price instead of running maximum to derive the fair value of the option. 

$$ 
V_{KO} (0) = E^Q [X \mathbf{1}_{M(t) < b}] = \hat{V}_{KO}(0) 
$$ 
 

1. Split the indicator function for multiple periods: 

$$ 
\mathbf{1} (M(T) < b) = \prod_{i = 1}^T \mathbf{1} (S(t_i) < b) 
$$ 

2. Substitute 1. in the expectation: 

$$ 
V_{KO} (0) = E^Q [ X \mathbf{1} (M(2) < b)] = E^Q [ X \mathbf{1} (S(1) < b) \mathbf{1} (S(2) < b) ] = E^Q [ \mathbf{1} (S(1) < b) E^Q_1 [ X \mathbf{1} (S(2) < b)]]
$$

At each recursive node i in (0, T), we get $\hat{V}_{KO} (i)$ as the inner terms. What about knock in options? 

$$ 
V_{KI} (0) = V(0) - V_{KO} (0) = V(0) - \hat{V}_{KO} (0) 
$$ 

- In continuous time, the price may trigger the barrier several times. To avoid multiplicity, we can modify the barrier, raising or lowering it slightly. We derive the modified $\hat{b}$ **view modification paper** 

## Path dependent options in binomial models ## 

 Asian option: $A(t) = \frac{1}{M} \sum_i^M S(t_i)$ 
 $X(t) = (K - A(t))^{+}$ 
 Asian put option can be either European or American. 

 Lookback call option: $M(t) = \operatorname{max}_{0 \leq t_i \leq t} S(t_i)$ 
 $ X(t)  = (M(t) - K)^{+} $

 If 
  $$ 
  \begin{align} X(t) = f(S(t)) \\ 
  f: R^{+} \to R \text{ is deterministic} \\ 
  f(x) = (x - k)^{+} \text{ call } f(x) = (k - x)^{+} \text{ put} \end{align}
  $$ 

  The pricing problem is Markovian, i.e. we solve for all t 

  $$ 
  V_X(t) = \operatorname{max} (f(S(t)), E^Q_t [V_X (t + \Delta t) e^{-n\Delta t}]) 
  $$

Given: 
$$ \begin{align} 
X(t) = (M(t) - K)^{+} \\ 
\text{Markowianize by addimg an auxiliary state variable} (t, S(t), M(t)) \text{ for lookback} \\ 
(t, S(t), A(t)) \text{ for Asian} 
\end{align}
$$ 

## MArkowianization on lookback options ## 

1. Define running max on $t_n$:

$$ S(t_n) = S_0 u^k d^{t_n - k} \quad M(t_n, S(t_n)) = \begin{cases} S(t_n) \\ \vdots \\ S_0 u^k \end{cases} 
$$


## Continuos time ## 

$\Delta t \to 0$
 
 $$ 
 \begin{align} \frac{B(t + \Delta t) - B(t)}{B(t)} = r(t) \Delta t \\ 
 \Omega: \text{infinite scenarios} \\ 
 \mathcal{P} \to \mathcal{F} \text{ filtration} \end{align}
 $$

Applying differential apprximation, we get 
$$ \begin{align} \frac{d B(t)}{B(t)} &= r(t) dt \\ 
d(ln B(t)) &= r(t) \\ 
\int_0^T d(ln B(t)) &= \int_0^T r(t) dt
B(T) = e^{\int_0^T r(t) dt}
\end{align}
$$ 

# Lecture 5 #

## Recap for riskless ## 

$$ \frac{\Delta B(t)}{B(t)} \approx \frac{B(t + \Delta t) - B(t)}{B(t)} 
$$ 

We approximate the preturns of the riskless asset in continuous time thorugh first order taylor approx 

$$ \int_0^T d(ln B(t)) = \int_0^T \frac{d B(t){B(t)}} = \int_0^T r(t) dt
$$ 

the term $ \int_0^T d(ln B(t)) $ equals $ ln B(T) - ln B(0) $ were the sec term is 0 and so 

$$ B(T) (\omega) = exp^{\int_0^T r(t \mid \omega ) dt}
$$ 


## For risky ## 

$$ \frac{\Delta S(t)}{S(t)} = \mu(t) \Delta t + \sigma (t) \Delta \Omega (t) 
$$ 

where $ \mu (t) \Delta t $ is the *t-expected component*
and $ W (t) \sim M (0, \Delta t)$ is an independent of $\mathcal{F(t)}$ component (noise)

Taking expectations: 

$$ E^p_t [\frac{\Delta S(t)}{S(t)}] = E^p_t [\mu(t) \Delta t + \sigma (t) \Delta \Omega (t)] = \mu(t) \Delta t + \sigma (t) E^p_t [ \Delta W (t)] = \mu (t) \Delta 
$$ 


In words: we expect to get the return equal to the t-expected component. 

Squaring: 

$$ E^p_t [ (\frac{\Delta S(t)}{S(t)})^2] =  E^P_t [ (\mu(t) dt)^2 + (\sigma(t) \Delta W(t))^2 + 2 \mu(t) \Delta t \sigma(t) \Delta W (t)] 
$$

To simplify, note $E^p [ \Delta W^2 (t)] \aprox \Delta t$ and $E^p (\Delta W (t)) = 0$ so we get: 

$$ (\mu (t) dt)^2 + \sigma^2 (t) \Delta t \approx \sigma^2 (t) \Delta t
$$ 

Since $(\Delta t)^2$ is small relative to $\Delta t$


## Wiener Process (st. brownian) ## 

$W$ is $\mathcal{F}$-adapted, $W(0) = 0$. W has continuous trajectories

W has continuous trajectories, and increments  $W(t + \Delta t) - W(t) \sim \eta (0, \Delta t) $ The idea is to add continuously increments of Brownian motion over time, and normality of the increments helps us derive properties of the process by relying on the central limit theorem. W is the only risk factor affecting the model (we can think of it as the aggregate riskiness of security S). 

- **Note**: W has continuous trajectories nowhere differentiable. Meaning: if $P(\Delta W > 0) = P(\Delta W \leq 0) = 50%$ If we plot the process, depending on how we "zoom" we can find a segment of the curve that changes direction locally (as we "zoom"). Therefore we cannot proxy the change in the function by a tangent. 

How to sum $ \int_0^{\tau}\sigma(t) \Delta W(t)$? We write: 

$$ \int_0^{\tau}\sigma(t) \frac{\Delta W(t)}{\Delta t} \Delta t
$$

As $\Delta t \to 0$, we get $\frac{\Delta W(t)}{Delta t} \approx \frac{\partial {W}}{\partial t}$, but we cannot do this because W is non differentiable. 

We must define an alternative way to sum the quantitites $\int_0^{\tau} \sigma(t) \Delta W(t)$ as $\Delta t \to 0$, where the integral is the **aggregate shock** on $\frac{\Delta S}{S}$ over $[0, \tau]$. We note: 

 1. $\sigma(t)$ is constant, so we can factor it out: 

$$ \int_0^{\tau} \sigma \Delta W(t) = \sigma \int_0^{\tau} \Delta W (t) = \sigma (W(\tau) - W(0)) = \sigma W(\tau) 
$$ 

2.
$$ \begin{array} \sigma(t) &= \sigma_0 in t \in [ 0, t_1) \\
\sigma(t) = \sigma_1 \end{array}
$$

$$
\begin{aligned}
\int_0^{\tau} \sigma(t)\,\Delta W(t)
&=
\int_0^{t_1} \sigma_0\,\Delta W(t)
+
\int_{t_1}^{\tau} \sigma_1\,\Delta W(t) \\[4pt]
&=
\sigma_0 \int_0^{t_1} \Delta W(t)
+
\sigma_1 \int_{t_1}^{\tau} \Delta W(t) \\[4pt]
&=
\sigma_0
\underbrace{W(t_1)}_{\eta(0,t_1)}
+
\sigma_1
\underbrace{\left(W(\tau)-W(t_1)\right)}_{\eta(0,\tau-t_1)} \\[4pt]
&\sim
\eta\left(
0,\,
\sigma_0^2 t_1
+
\sigma_1^2(\tau-t_1)
\right).
\end{aligned}
$$

Where the etas indicate that the increments of Brownian motion are iid normal rv. 

3. 
$$ \sigma(t) = \begin{cases} \sigma_0 \quad t \in [0, t_1) \\
                            \underbrace{\sigma (t_1)}_{\mathcal{F}_{t_1}-\text{meas}} \quad t \in [t_1, \tau]
                \end{cases}
$$ 


Now 

$$ \int_0^{\tau} \sigma(t) d W(t) = \sigma_0 W(t_1) + \underbrace{\sigma(t_1)}_{\mathcal{F}_{t_1}-\text{meas}} \underbrace{(W(\tau) - W(t_1))}_{\text{indep of $\mathcal{F}_1$}}
$$

Next note: 

$$ E^P [ \int_0^{\tau} \sigma(t) d W(t)] = 0 \quad E^P [(\int_0^{\tau} \sigma(t) dW(t))^2] = \int_0^{\tau} E^P [\sigma^2 (t)] dt = \sigma_0^2 t_1 + E^P [ \sigma^2 (t_1)] (\tau - t_1)
$$

the intermediate interchange of deriv folow from Ito's identity + Fubini/Tonelli (**explain**)

$$ 0 = E^P [\sigma_0 W(t_1) + \sigma (t_1) (W(\tau) - W(t_1))] = \sigma_0 E^P [W(t_1) ] + E^P [E^P_{t_2}] [ \sigma (t_1) (W(\tau) - W(t_1))] = 0
$$ 

We verify the second moment: 

$$
\begin{aligned}
&E^P \left[
\left(
\sigma_0 W(t_1)
+
\sigma(t_1)\bigl(W(\tau)-W(t_1)\bigr)
\right)^2
\right]
\\[4pt]
&=
\sigma_0^2 E^P\left[W(t_1)^2\right]
\\
&\quad+
E^P\left[
E^P_{t_1}\left[
\sigma^2(t_1)
\bigl(W(\tau)-W(t_1)\bigr)^2
\right]
\right]
\\
&\quad+
2\sigma_0
E^P\left[
E^P_{t_1}\left[
W(t_1)\sigma(t_1)
\bigl(W(\tau)-W(t_1)\bigr)
\right]
\right]
\\[6pt]
&=
\sigma_0^2 t_1
\\
&\quad+
E^P\left[
\sigma^2(t_1)
E^P_{t_1}\left[
\bigl(W(\tau)-W(t_1)\bigr)^2
\right]
\right]
\\
&\quad+
2\sigma_0
E^P\left[
W(t_1)\sigma(t_1)
E^P_{t_1}\left[
W(\tau)-W(t_1)
\right]
\right]
\\[6pt]
&=
\sigma_0^2 t_1
\\
&\quad+
E^P\left[
\sigma^2(t_1)
\left(
\operatorname{Var}_{t_1}
\bigl(W(\tau)-W(t_1)\bigr)
+
\left(
E^P_{t_1}
\bigl[W(\tau)-W(t_1)\bigr]
\right)^2
\right)
\right]
\\
&\quad+
2\sigma_0
E^P\left[
W(t_1)\sigma(t_1)\cdot 0
\right]
\\[6pt]
&=
\sigma_0^2 t_1
+
E^P\left[
\sigma^2(t_1)
\left(
(\tau-t_1)+0^2
\right)
\right]
+
0
\\[6pt]
&=
\sigma_0^2 t_1
+
E^P\left[
\sigma^2(t_1)(\tau-t_1)
\right]
\\[6pt]
&=
\boxed{
\sigma_0^2 t_1
+
E^P\left[\sigma^2(t_1)\right](\tau-t_1)
}.
\end{aligned}
$$


where $E^P(\Delta W(t))^2 = Var(\Delta W) + 0 = \tau - t_1 \text{ on } t \in [t_1, \tau]$

4. Now we want to calculate the covariance between Brownian increments (random shocks): 
$$ E^P [ \int_0^{\tau} \sigma_1 (t) d W(t) \int_0^{\tau} \sigma_2 (t) dW(t)] = \int_0^{\tau} E^P [\sigma_1 (t) \sigma_2 (t)] dt 
$$ 

5. $ \int_0^{\tau} \sigma(t) dW(t) $ is a P-martingale on $t \in [0, \tau]$ 

6. $\int_0^{\tau} \sigma(t) d W(t)$ is a **stochastic integral** of $\sigma \text{ in } [0, \tau]$. 

We have $ d M(t) = \sigma(t) d W(t) $

$$ E^P_t [d M(t)] = \sigma (t) E^P_t [ d W(t)] = 0 
$$ 

where $ W(t + \Delta t) - W(t) $ is F indep. and has mean zero, thus the process is indeed a martingale (**why**?) 

## Switching from returns to levels ## 


We know: 

$$ \frac{d S(t)}{S(t)} = \mu(t) dt + \sigma(t) d W(t) 
$$ 

we would like to determine the current price of the asset, $S(t)$

Problem: $ f(t, x): [0, T] \times R^{+} \to R$, cont. differential wrt t and twice cont differentiable wrt $x \in R^{+}$. 
$$d f(t, S(t)) = ?$$

$$ d f(t, B(t)) = \frac{\partial{f}}{\partial{t}} (t, B(t)) dt + \frac{\partial f}{\partial{x}} (t, B(t)) dB(t)
$$

the total variation is defined by the formula above. 

Now: 

$$ d f(t, S(t)) = \frac{\partial{f}}{\partial{t}} (t, S(t)) dt + \frac{\partial{f}}{\partial{x}} (t, S(t)) dS(t)
$$

Remember that the first moment of differential percentage change is given by:

$$ 
E^P_t [ \frac{d S(t)}{S(t)}] = \mu(t) dt 
$$

and the second moment by: 

$$ E^P_t [ (\frac{d(S (t))}{S(t)})^2] = \mu^2 (t) (dt)^2 + \sigma^2 (t) dt 
$$

With 

$$ E^P_t [ (d S(t))^2] = s^2 (t) (\sigma^2 (t) dt + \mu^2 (dt)^2) \approx s^2 (t) \sigma^2 (t) dt 
$$ 

Thorugh sec order Taylor approx we write: 

$$
\begin{aligned}
df(t,S(t))
&=
\frac{\partial f}{\partial t}\,dt
+
\frac{\partial f}{\partial x}\,dS
+
\frac{1}{2}
\frac{\partial^2 f}{\partial t^2}\,(dt)^2
\\
&\quad+
\frac{\partial^2 f}{\partial t \partial x}\,dt\,dS
+
\frac{1}{2}
\frac{\partial^2 f}{\partial x^2}\,(dS)^2.
\end{aligned}
$$

Plugging in the derived expressions for $d S(t)$ and $(d S(t))^2$ and cancelling the "little" terms, we arrive to the statement of **Ito's Lemma**: 

$$
\begin{aligned}
df(t,S(t))
&=
\frac{\partial f}{\partial t}(t,S(t))\,dt
+
\frac{\partial f}{\partial x}(t,S(t))
\left[
\mu(t,S(t))\,dt
+
\sigma(t,S(t))\,dW(t)
\right]
\\
&\quad+
\frac{1}{2}
\frac{\partial^2 f}{\partial x^2}(t,S(t))
\sigma^2(t,S(t))\,dt
\\[4pt]
&=
\left[
\frac{\partial f}{\partial t}(t,S(t))
+
\mu(t,S(t))
\frac{\partial f}{\partial x}(t,S(t))
+
\frac{1}{2}
\sigma^2(t,S(t))
\frac{\partial^2 f}{\partial x^2}(t,S(t))
\right]dt
\\
&\quad+
\sigma(t,S(t))
\frac{\partial f}{\partial x}(t,S(t))
\,dW(t).
\end{aligned}
$$

And we can get the solution by substituting $ f(t, S(t)) = ln S(t)$ $f(t, x) = ln x$ $\frac{\partial{f}}{\partial{t}} = 0$ $\frac{\partial{f}}{\partial{t}} = 0$ $\frac{f}{x} = \frac{1}{x}$ $\frac{\partial^2 f}{\partial{x}} = - 1/x^2$

We write: 

$$ \int_0^{\tau} d (ln S(t)) = \int_0^{\tau} (\mu(t) - \frac{\sigma^2 (t)}{2}) dt + \int_0^{\tau} \sigma(t) d W(t)
$$ 

We cna simplify the first term to $ln S(\tau) - ln S(0)$ and then: 

$$ ln \frac{S(\tau)}{S(0)} = \int_0^{\tau} (\mu - \sigma^2/2) dt + \int_0^{\tau} \sigma dW(t) = \underbrace{(\mu - \frac{\sigma^2}{2}) \tau + \sigma W(\tau)}_{\text{Generalized brownian motion}}
$$ 

Therefore: 

$$ ln \frac{S(\tau)}{S(0)} \sim \eta ((\mu - \frac{\sigma^2}{2})\tau, \sigma^2 \tau) \implies S \text{ is "log-normal"}
$$ 

and 

$$ S(\tau) = S(0) exp^{(\mu - \frac{\sigma^2}{2}) \tau + \sigma W(\tau)} 
$$

We have that S is a deterministic component relying on t and W is the risk factor in t, so observing S is equivalen to observing W in our framework. 

## Strategies ## 

- Let $(\nu_0, \nu_1) = \nu$ and $\nu (t) \text{ is } \mathcal{F}_t \text{-measurable for all t}$

- Suppose S pays dividends. In $ (t, t + \Delta t)$ S pays $d D(t) = q S(t) dt$, $q \geq 0$ is the dividend yield. 

$$ d G(t) = \underbrace{d S(t)}_{\text{capital gain}} + \underbrace{d D(t)}_{\text{cashflow}} = d S(t) + q S(t) dt 
$$ 

## Self financing strategy with dividends ## 

$ \nu (t) $ strategy at t, at  $ t + dt $ it delivers (future value of strategy $\mu$): 

$$ \nu_0 (t) B(t + dt) + \nu_1 (t) (S(t + dt) + q S(t) dt) = V_{\nu} (t + dt)
$$ 


The instantaneous change in value is given by: 

$$ d V_{\nu} (t) = V_{\nu} (t + \Delta t) - V_{\nu} (t) = \nu_0(t) B(t + dt) + \nu_1 (t) S(t + dt) + \nu_1 (t) q S(t) ft - (\nu_0 (t) B(t) + \nu_1 (t) S(t)) = \nu_0 (t) d Bt + \nu_1 (t) (d S (t) + S(t) q dt)
$$ 

Hence we define $\nu$ self financing if: 

$$ d V_{\nu} (t) = \nu_0 (t) d B(t) + \nu_1 (t) (d S(t) + S(t) f dt)
$$ 

 

and in Discounted terms: 

$$ d \tilde{V}_{\nu} (t) = \nu_1 (t) (d \tilde{S}(t) + q \tilde{S} (t) dt)
$$

- **Arbitrage**: $\nu$ is self-financing, $V_{\nu}(0) \leq 0$
and $P(V_{\nu}(\tau) \geq 0) = 1$ and $ P(V_{\nu} (\tau) > 0) > 0$
- If no arbitrage is satisfies, we can find a risk neutral measure (not unique, uniqueness given by second fundamental theorem). 

- **Definition**: Q is RN, equivalent to P and the gain process of S discounted with $B(t)$ is a Q-martingale: 

$$ 
d G(t) = d S(t) + q S(t) dt 
$$

We have (why?)

$$ E^Q_t [d \tilde{G} (t)] = 0 
$$

And we want to find Q RN: 

$$ d \tilde{G} (t) = d \tilde{S} (t) + q \tilde{S} (t) dt 
$$

The discounted price is given by: 


$$ d \tilde{S} (t) = d (S(t) e^{-rt}) = (d S (t)) e^{-nt} - (r e^{-rt}dt ) S(t) = (e^{-rt} S(t)) ((\mu - r) dt + \sigma d W(t))
$$

## Market price of risk ## 

- Set $ \alpha \in \mathbf{R}$ s.t. $ \alpha = \frac{\mu + q - r}{\sigma}$. where $\mu$ is the capital gain, $q$ is the dividend gain, $r$ is the instantaneius discount rate and $\sigma$ is the volatility of returns. 
- By **Girsanov** theorem, there exists a unique $Q = Q(\alpha)$ s.t.:

$$ d W^Q(t) = d W(t) + \alpha dt 
$$

defines a std BM $W^Q$. 

And

$$ d \tilde{G} = \tilde{S} (t) (\alpha \sigma dt + \sigma d W(t) ) = \tilde{S}(t) \sigma \underbrace{ (\alpha dt + d W(t))}_{d W^Q (t)} 
$$

- NA holds by first fundamental theorem, if Q is unique, then the market is complete by the second fundamental theorem. 

## Dynamics of S wrt Q ## 

1. 

$$ \frac{d S(t)}{S(t)} = \mu dt + \sigma d W(t) = \mu dt + \sigma d W^Q (t) - \sigma \alpha dt = (r - q) dt + \sigma d W^Q(t)
$$ 


2. $\nu$ is self financing, implying $\tilde{V}_{\nu}$ is a Q-martingale. Indeed: 

$$ d \tilde{V}_{\nu}(t) = \nu_1 (t) (d \tilde{S}(t) + q \tilde{S}(t) dt) = \nu_1 \tilde{S} (t) \sigma d W^Q(t) 
$$

Moreover, 

$$ E^Q_t [ d \tilde{V}_{\nu} (t) ] = \nu_1 (t) \tilde{S} (t) \sigma E^Q_t [dW^Q (t)] = 0 \implies \text{discounted value is a Q-martingale}
$$

## Derviing the risk neutral measure for European option from risk neutral measure for self financing strategies ## 

1. Let there exist a Q RN. By first fundamental theorem, this implies no arbotrage. 

2. $\nu$ is self financing, $V_{\nu} (0) \leq 0$, $Q(\tilde{V}_{\nu} (T) \geq 0) = 1$ and $Q (\tilde{V} (\tau) > 0) > 0$

3. $V(0) = \tilde{V}_{\nu} (0) = E^Q [ \tilde{V}_{\nu} (\tau)] > 0 \implies V_{\nu}(0) > 0 \implies NA$